
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    groups = {}
    
    for row in cur:
        key = (row['cust'], row['prod'])
        
        # Check all grouping variable conditions
        match_1 = row['state']=='NY' and row['year']==2020
        if key not in groups:
            groups[key] = {
                'cust': row['cust'], 'prod': row['prod'],
                '1_sum_quant': 0
            }
        
        # Update aggregates
        groups[key]['1_sum_quant'] += row['quant'] if match_1 else 0
    
    # Prepare results
    result = []
    for key, group_data in groups.items():
        result_row = {
            'cust': group_data['cust'], 'prod': group_data['prod'],
            'sum_quant_ny': group_data['1_sum_quant']
        }
        # Apply HAVING clause
        if True:
            result.append(result_row)
    
    _global = result
    
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    